apiVersion: apps/v1
kind: Deployment
metadata:
  name: sampledockyaml-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app:sampleDockYaml
  template:
    metadata:
      labels:
        app: sampleDockYaml
    spec:
      containers:
      - name: dockersamplerepos
        image: samplescrs.azurecr.io/dockersamplerepos:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: dsconsn

---
apiVersion: v1
kind: Service
metadata:
  name: sampledockyaml
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: sampleDockYaml
